name: water

on:
  watch:
    types: [started]
  schedule:
    - cron: '30 1-9,11-13 * * *'

jobs:
  water:
    name: Water notice
    runs-on: ubuntu-latest
    steps:
      - name: Push message
        run: |
          MSG="饮水鸟已经喝完水了，你呢"
          HOUR=$((`TZ='Asia/Shanghai' date +%_H`))
          if [ $HOUR -ge 21 ]; then
            MSG="饮水鸟要休息了，你也是"
          fi
          curl -G --data-urlencode "key=$WATER_CHANNEL" --data-urlencode "head=正要喝水" --data-urlencode "body=$MSG" "http://push.ijingniu.cn/send"
        env:
          WATER_CHANNEL: ${{ secrets.WATER_CHANNEL }}
