name: water

on:
  watch:
    types: [started]
  schedule:
    - cron: '30 1-9,11-13 * * *'

jobs:
  water:
    name: Water notice
    runs-on: ubuntu-latest
    steps:
      - name: Push message
        run: curl "http://push.ijingniu.cn/send?key=$WATER_CHANNEL&head=%E6%AD%A3%E8%A6%81%E5%96%9D%E6%B0%B4&body=%E9%A5%AE%E6%B0%B4%E9%B8%9F%E5%B7%B2%E7%BB%8F%E5%96%9D%E5%AE%8C%E6%B0%B4%E4%BA%86%EF%BC%8C%E4%BD%A0%E5%91%A2"
        env:
          WATER_CHANNEL: ${{ secrets.WATER_CHANNEL }}